language: java
sudo: required
jdk:
  - oraclejdk7
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: abc@xyz.com
  password: asdfgh12
  organization: 
  space: dev
  on:
    branch: master
  
